<highlight>
<T1>Mitt Romney's refusal to release tax returns in the critical years of his income accumulation has done little to dispel the legitimate concern that arises from hints buried in his scant disclosure to date: Did he augment his wealth through highly aggressive tax stratagems of questionable validity?</T1>

<T1.1>Opinion: Why won't Romney release more tax returns?</T1.1>
<T1.1.1>He served as a member of the Marriott board of directors for many years.</T1.1.1>

<T1.2>The Son of Boss transaction was vulnerable to attack on at least two grounds.</T1.2>
<T1.2.1>In his key role as chairman of the Marriott board's audit committee, Romney approved the firm's reporting of fictional tax losses exceeding $70 million generated by its Son of Boss transaction.</T1.2.1>
<T1.2.1.1>In the Marriott case, the IRS raised both arguments and won on the first interpretive issue.</T1.2.1.1>
<T1.2.1.1.1>In mid-1994, for example, roughly contemporaneously with Marriott's execution of its Son of Boss trade and well before Marriott filed its return claiming the artificial loss, the highly respected Tax Section of the New York Bar Association filed a public comment with the U.S. Treasury and IRS urging rejection of the technical claims made by promoters of such schemes.</T1.2.1.1.1>

<T1.3>Romney's campaign staff has attempted to deflect responsibility, arguing that he relied on Marriott's tax department and advisers.</T1.3>

<T1.3.1>This claim is disingenuous.</T1.3.1>

<T1.3.2>What emerges from this window into corporate tax compliance behavior is the picture of an executive who was willing to go to the edge, if not beyond, to bend the rules to seek an unfair advantage, and then hide behind the advice of so-called experts to deflect criticism when a scheme backfires.</T1.2.2>
</highlight>
